[2025-05-18 02:51:42] [info] –ó–∞–≥—Ä—É–∂–µ–Ω–æ [36m1[0m –∑–∞–¥–∞—á –≤ –ø–∞–º—è—Ç—å
[2025-05-18 02:51:42] [info] –°–±—Ä–æ—Å –≤—ã–ø–æ–ª–Ω—è—é—â–∏—Ö—Å—è –∏ –æ—à–∏–±–æ—á–Ω—ã—Ö –∑–∞–¥–∞—á –≤ —Å—Ç–∞—Ç—É—Å Pending...
[2025-05-18 02:51:42] [info] –°–±—Ä–æ—à–µ–Ω–æ [33m1[0m –∑–∞–¥–∞—á.
[2025-05-18 02:51:42] [info] –ó–∞–≥—Ä—É–∂–µ–Ω–æ [36m800[0m –ø—Ä–æ–∫—Å–∏ –≤ –ø–∞–º—è—Ç—å
[2025-05-18 02:51:42] [info] –ó–∞–≥—Ä—É–∂–µ–Ω–æ [36m800[0m –∞–∫–∫–∞—É–Ω—Ç–æ–≤ –≤ –ø–∞–º—è—Ç—å
[2025-05-18 02:51:50] [info] Initialized TwitchService for channel: semtrip
[2025-05-18 02:51:50] [info] –ó–∞–ø—É—Å–∫–∞–µ—Ç—Å—è Twitch-—Å–µ—Ä–≤–∏—Å –¥–ª—è –∑–∞–¥–∞—á–∏ 2 (URL: https://www.twitch.tv/semtrip)
[2025-05-18 02:51:50] [info] Checking stream status for [36msemtrip[0m
[2025-05-18 02:51:52] [info] [Stream Status] semtrip - Online
[2025-05-18 02:51:52] [info] –°—Ç—Ä–∏–º https://www.twitch.tv/semtrip –≤ —ç—Ñ–∏—Ä–µ. –ù–∞—á–∏–Ω–∞–µ–º –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–µ –∑–∞–¥–∞—á–∏ 2.
[2025-05-18 02:51:52] [info] Starting 100 bots (ramp-up 1 min)
[2025-05-18 02:51:57] [info] –ó–∞–¥–∞—á–∞ 2 –∑–∞–ø—É—â–µ–Ω–∞ –Ω–∞ 00:33:00 (1980 —Å–µ–∫—É–Ω–¥)
[2025-05-18 02:51:57] [info] –ó–∞–¥–∞—á–∞ 2: —Å–ª–µ–¥—É—é—â–∏–π —á–µ–∫ —á–µ—Ä–µ–∑ 60 —Å–µ–∫...
[2025-05-18 02:51:57] [info] Bot ID:[0] starting now
[2025-05-18 02:51:57] [info] [BOT 0] Starting with proxy socks5://rlF97R:IL9MJzmIaa@109.248.142.14:1051
[2025-05-18 02:51:57] [info] Bot ID:[1] will start in 0.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[2] will start in 1.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[3] will start in 1.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[4] will start in 2.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[5] will start in 3.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[6] will start in 3.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[7] will start in 4.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[8] will start in 4.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[9] will start in 5.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[10] will start in 6.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[11] will start in 6.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[12] will start in 7.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[13] will start in 7.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[14] will start in 8.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[15] will start in 9.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[16] will start in 9.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[17] will start in 10.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[18] will start in 10.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[19] will start in 11.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[20] will start in 12.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[21] will start in 12.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[22] will start in 13.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[23] will start in 13.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[24] will start in 14.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[25] will start in 15.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[26] will start in 15.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[27] will start in 16.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[28] will start in 16.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[29] will start in 17.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[30] will start in 18.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[31] will start in 18.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[32] will start in 19.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[33] will start in 19.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[34] will start in 20.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[35] will start in 21.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[36] will start in 21.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[37] will start in 22.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[38] will start in 22.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[39] will start in 23.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[40] will start in 24.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[41] will start in 24.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[42] will start in 25.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[43] will start in 25.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[44] will start in 26.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[45] will start in 27.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[46] will start in 27.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[47] will start in 28.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[48] will start in 28.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[49] will start in 29.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[50] will start in 30.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[51] will start in 30.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[52] will start in 31.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[53] will start in 31.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[54] will start in 32.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[55] will start in 33.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[56] will start in 33.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[57] will start in 34.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[58] will start in 34.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[59] will start in 35.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[60] will start in 36.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[61] will start in 36.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[62] will start in 37.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[63] will start in 37.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[64] will start in 38.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[65] will start in 39.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[66] will start in 39.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[67] will start in 40.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[68] will start in 40.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[69] will start in 41.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[70] will start in 42.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[71] will start in 42.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[72] will start in 43.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[73] will start in 43.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[74] will start in 44.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[75] will start in 45.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[76] will start in 45.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[77] will start in 46.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[78] will start in 46.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[79] will start in 47.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[80] will start in 48.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[81] will start in 48.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[82] will start in 49.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[83] will start in 49.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[84] will start in 50.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[85] will start in 51.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[86] will start in 51.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[87] will start in 52.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[88] will start in 52.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[89] will start in 53.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[90] will start in 54.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[91] will start in 54.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[92] will start in 55.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[93] will start in 55.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[94] will start in 56.4 seconds
[2025-05-18 02:51:57] [info] Bot ID:[95] will start in 57.0 seconds
[2025-05-18 02:51:57] [info] Bot ID:[96] will start in 57.6 seconds
[2025-05-18 02:51:57] [info] Bot ID:[97] will start in 58.2 seconds
[2025-05-18 02:51:57] [info] Bot ID:[98] will start in 58.8 seconds
[2025-05-18 02:51:57] [info] Bot ID:[99] will start in 59.4 seconds
[2025-05-18 02:51:57] [error] [BOT 0] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6381010>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6381010>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:57] [info] [BOT 0] Stopped
[2025-05-18 02:51:57] [info] Bot ID:[0] started successfully
[2025-05-18 02:51:58] [info] Bot ID:[1] starting now
[2025-05-18 02:51:58] [info] [BOT 1] Starting with proxy socks5://rlF97R:IL9MJzmIaa@46.8.10.65:1051
[2025-05-18 02:51:58] [error] [BOT 1] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6841E50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6841E50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:58] [info] [BOT 1] Stopped
[2025-05-18 02:51:58] [info] Bot ID:[1] started successfully
[2025-05-18 02:51:58] [info] Bot ID:[2] starting now
[2025-05-18 02:51:58] [info] [BOT 2] Starting with proxy socks5://rlF97R:IL9MJzmIaa@45.11.20.219:1051
[2025-05-18 02:51:59] [error] [BOT 2] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842D50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842D50>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:59] [info] [BOT 2] Stopped
[2025-05-18 02:51:59] [info] Bot ID:[2] started successfully
[2025-05-18 02:51:59] [info] Bot ID:[3] starting now
[2025-05-18 02:51:59] [info] [BOT 3] Starting with proxy socks5://rlF97R:IL9MJzmIaa@213.226.101.115:1051
[2025-05-18 02:51:59] [error] [BOT 3] Fatal error: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842210>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
Traceback (most recent call last):
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 96, in start
    streams = await asyncio.get_event_loop().run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "c:\Program Files\Python313\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\semtrip.DESKTOP-QDM923H\Documents\GitHub\stream_shop_service\backend\Service\Twitch\main_bot.py", line 98, in <lambda>
    lambda: self.streamlink.streams(f"https://www.twitch.tv/{self.channel}")
            ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\session.py", line 153, in streams
    return plugin.streams(**params)
           ~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugin\plugin.py", line 401, in streams
    ostreams = self._get_streams()
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 986, in _get_streams
    return self._get_hls_streams_live()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 915, in _get_hls_streams_live
    sig, token, restricted_bitrates = self._access_token(True, self.channel)
                                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 884, in _access_token
    response, *data = self.api.access_token(is_live, channel_or_vod)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 516, in access_token
    return self.call(
           ~~~~~~~~~^
        query,
        ^^^^^^
    ...<29 lines>...
        ),
        ^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\plugins\twitch.py", line 314, in call
    return self.session.http.post(
           ~~~~~~~~~~~~~~~~~~~~~~^
        "https://gql.twitch.tv/gql",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\semtrip.DESKTOP-QDM923H\AppData\Roaming\Python\Python313\site-packages\streamlink\session\http.py", line 196, in request
    raise err from None  # TODO: fix this
    ^^^^^^^^^^^^^^^^^^^
streamlink.exceptions.PluginError: Unable to open URL: https://gql.twitch.tv/gql (SOCKSHTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001FDA6842210>: Failed to establish a new connection: 0x02: Connection not allowed by ruleset')))
[2025-05-18 02:51:59] [info] [BOT 3] Stopped
[2025-05-18 02:51:59] [info] Bot ID:[3] started successfully
[2025-05-18 02:52:00] [info] Bot ID:[4] starting now
[2025-05-18 02:52:00] [info] [BOT 4] Starting with proxy socks5://rlF97R:IL9MJzmIaa@188.130.142.220:1051
